project_name: checkpointz

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make build-web
builds:
  - env:
      - CGO_ENABLED=0
    binary: checkpointz-{{.Version}}
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goarch: 386
    ldflags:
      - -s -w -X github.com/ethpandaops/checkpointz/pkg/version.Release={{.Tag}} -X github.com/ethpandaops/checkpointz/pkg/version.GitCommit={{.ShortCommit}}
    mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  ## Scratch
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: goreleaser-scratch.Dockerfile
    image_templates:
      - "ethpandaops/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ethpandaops/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: goreleaser-scratch.Dockerfile
    image_templates:
      - "ethpandaops/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ethpandaops/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  ## Debian
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: goreleaser-debian.Dockerfile
    image_templates:
      - "ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-amd64"
      - "ethpandaops/{{ .ProjectName }}:debian-latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: goreleaser-debian.Dockerfile
    image_templates:
      - "ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-arm64v8"
      - "ethpandaops/{{ .ProjectName }}:debian-latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  ## Scratch
  - name_template: ethpandaops/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-amd64
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ethpandaops/{{ .ProjectName }}:{{ .Version }}-arm64
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ethpandaops/{{ .ProjectName }}:latest
    image_templates:
      - ethpandaops/{{ .ProjectName }}:latest-amd64
      - ethpandaops/{{ .ProjectName }}:latest-arm64v8

  ## Debian
  - name_template: ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-amd64
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-arm64v8
  - name_template: ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-arm64
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-arm64v8
  - name_template: ethpandaops/{{ .ProjectName }}:debian-latest
    image_templates:
      - ethpandaops/{{ .ProjectName }}:debian-latest-amd64
      - ethpandaops/{{ .ProjectName }}:debian-latest-arm64v8